### ISSUE TITLE
Package is not published as a NPM module

### ISSUE THREAD

**Issue by binayatdelhi** [inspect-js/is-boolean-object#24]
Please publish this latest package on NPM.
When I'm doing "npm view is-boolean-object" I can see only is-boolean-object@1.0.0

Latest tag 1.1.0 is not published. Getting following error
is-boolean-object: No matching version found for is-boolean-object@^1.1.0

**Comment by ljharb** [comment]
Sounds like you have an internal registry that isn’t properly updated.

That command works fine for me, and https://npmjs.com/is-boolean-object clearly shows v1.1.0.
